### PR TITLE
fix example macro code error on `/`

### PR DESCRIPTION
**Pull request by tachibana-shin**

### CODE REVIEW

**Comment by tachibana-shin** [comment]
pr looks like https://github.com/crystal-lang/crystal-website/pull/75

**Comment by beta-ziliani** [comment]
Hi @tachibana-shin , thank you for caring! 🙇 We are relaunching the website now, and this particular example is fixed. You can sneak peek at the current proposal here:
https://deploy-preview-730--crystal-website.netlify.app/#macros

**Comment by tachibana-shin** [comment]
> Hi @tachibana-shin , thank you for caring! 🙇 We are relaunching the website now, and this particular example is fixed. You can sneak peek at the current proposal here: https://deploy-preview-730--crystal-website.netlify.app/#macros

What should I do with this PR?

**Comment by straight-shoota** [comment]
Let's just close this. Thank you and sorry for the inconvenience ❤️

**Pull request closed without merging**
