### PR TITLE
Installation instructions: rework for all platforms

### PR DESCRIPTION
**Pull request by ftarulla**

### CODE REVIEW

**Comment by bcardiff** [comment]
@ftarulla I think I missed that Kubuntu should cover the same content as ubuntu. Official repo and linuxbrew options should be added aswell and it should be reordered between ubuntu and debian I guess. I'm sorry I didn't see that before.

**Comment by straight-shoota** [comment]
The paths don't work. Links are generated for `/install/<platform>` but the files are at `/install/<platform>.html`. I'm not sure if S3 can be configured to serve these files at a URL without the extensions.

Otherwise, the new pages need a permalink configuration (can be configured centrally in `_config.yml`).

**Comment by bcardiff** [comment]
Yikes. How I missed that in stg. Thanks.

**Comment by straight-shoota** [comment]
A few other notes regarding this change. I didn't get to review this properly before merging.

* I'd reorder the platforms, put the most important ones first. Probably something like macOS, ubuntu, arch, alpine, wsl at the top. Sources and tar.gz should be last. And we should add Docker instructions. Bigger icons would also be nice.
* It would be nice to have `Edit this page` links, directly linking to the edit page here on Github. Might be put under `Found any issues?`.
* We need a `/docs` page that links to installation, API and language reference (cf #57)
* We need a proper `Getting started` guide with a short introduction to Crystal, which can be linked at "Done installing?" "Learn" sounds not very welcoming. Calling it "Getting started" is better.

**Comment by bcardiff** [comment]
Regarding the ordering, the criteria was to put first the distros/platforms with official distribution channels.

As long as the top 4 are the current ones: sources, targz, mac, ubuntu I am happy to accept other criteria.

**Comment by bcardiff** [comment]
Platform detection and ordering based on global user base could be another option.

I wanted to have a clear menu for the users to pick their distro context and discover available options from there. And prevent them to go through ubuntu + snap + linuxbrew for example.

**Pull request merged**
