### PR TITLE
Remove *Docs* page and redirect to *Crystal Book*

### PR DESCRIPTION
**Pull request by straight-shoota**
The [docs page](https://crystal-lang.org/docs) and the landing page of the [Crystal Book](https://crystal-lang.org/reference/) share the same purpose and have a lot of duplication.

The book has essentially taken over the function of the docs page since the introduction of its landing page in https://github.com/crystal-lang/crystal-book/pull/493. It serves as a central hub for documentation materials for Crystal and incorporates not only resources in the book itself, but also in other locations (such as the website). It's much more advanced than the "old" docs page.

This patch removes the *Docs* page and replaces it with a redirect to the book. 

For the redirect I'm adding the plugin `jekyll-redirect-from` which should be a useful helper for similar tasks as well.

This is essentially a revert of #95 🤷

### CODE REVIEW

**Comment by straight-shoota** [comment]
Most of the links from the current docs page are also on the Book landing page with two exceptions (well, actually three but we can ignore that the book doesn't link to itself):

* *Media*: Logos and style guide (https://crystal-lang.org/media)
* *Shards documentation*: Documentation for official shards. [crystal-db](http://crystal-lang.github.io/crystal-db/api/latest/)

I'm not sure a reference to the media page fits well into the Book's landing page. I'd rather see this on the website, but we'll have to incorporate it into the efforts to overhault the navigation system (https://github.com/crystal-lang/crystal-website/issues/284).

The API docs to `crystal-db` are so far a solitary item of shard's documentation. I don't think it makes much sense to link them from the language docs. It's an independent shard (even when it's in `crystal-lang` org) and documentation for it is linked from the shard itself. So I think we can just drop this.

**Comment by beta-ziliani** [comment]
Just FTR there is another link missing: the wiki (there are just some inner links to it).

**Review by beta-ziliani — APPROVED** [review]
To be merged after #319

**Comment by beta-ziliani** [comment]
I added the wiki to the new (old) docs page:
https://github.com/crystal-lang/crystal-book/pull/628

**Pull request merged**
