### PR TITLE
Refactor example tabs interaction

### PR DESCRIPTION
**Pull request by straight-shoota**
Refactor the example tabs implementation with a horizontal scroll pane and JS interaction.
The vertical scroll position now does not jump when selecting a tab.
Also horizontal scrolling is possible in the tab pane, allowing for an alternative navigation.

Inspired by https://web.dev/articles/building/a-tabs-component

### CODE REVIEW

**Comment by beta-ziliani** [comment]
I'm completely failing to see a difference

**Comment by beta-ziliani** [comment]
In FF there's no real difference, is there? And from what I can understand in Chrome the change without the js is good enough to avoid it from jumping at each click of the tab. So is it really necessary?

**Comment by straight-shoota** [comment]
Yes, there's a difference and it's necessary. The JS handler prevents absolutely any vertical scrolling. This could happen even in Firefox in some situations (the viewport would jump when clicking the link while scrolled down, for example).
And horizontal scroll is pretty nice to swipe through the list, especially on touch devices.

**Comment by beta-ziliani** [comment]
There's a bug when scrolling horizontally in the examples panel: the dashed border of the selected tab stays:
image


We can probably ditch the dash rounded box entirely.

**Comment by straight-shoota** [comment]
That's a missing blur action because we prevent the event default. Fixed in latest commit.

**Review by beta-ziliani — APPROVED** [review]
🚀

**Pull request merged**
