### PR TITLE
Enable pretty URLs for pages

### PR DESCRIPTION
**Pull request by straight-shoota**
This changes the paths for pages to use pretty URLs.

It currently affects the following paths:
```
community/governance.html -> community/governance
docs.html -> docs
sponsors/original-sponsors.html -> sponsors/original-sponsors
learning/crystal_programming.html -> learning/crystal-programming
```
`404.html` is explicitly excluded.

Still missing redirects from the old `.html` paths to the new ones to keep existing links working.

Ref: #346

### CODE REVIEW

**Comment by matiasgarciaisaia** [comment]
Can you add the blogposts + provide the full list of redirections we should add? And we then maybe sync to merge + deploy the redirections at the same time.

**Comment by matiasgarciaisaia** [comment]
We need to reset the redirections on every deploy since we're using `aws s3 sync` with the `--delete` option (which will delete the redirections every time).

We may be able to hack something to avoid that, but I guess that's OK.

The hard-coded list of URLs (_path-ish's_, actually) is so we only support legacy URLs (instead of allowing future posts to have a .html entry too).

**Comment by straight-shoota** [comment]
So should we merge this? I think it should be good now.

**Comment by matiasgarciaisaia** [comment]
Yes! If you think it looks good, let's merge it :shipit:

**Pull request merged**
