### PR TITLE
Add link to release notes on blog index

### PR DESCRIPTION
**Pull request by straight-shoota**
grafik

### CODE REVIEW

**Comment by beta-ziliani** [comment]
I find it too small. The original design is better in this regard.

image

**Comment by straight-shoota** [comment]
Updated:

grafik

**Comment by beta-ziliani** [comment]
Is there a reason it's not in the same level as the first post, as in the design?

**Comment by straight-shoota** [comment]
Yeah, positioning it there would be quite hard to implement as it needs lots of special case layouting. So I did the simple thing first. That's not ideal, of course, and we can invest into enhancing this. But we'll also need to define the layout for small and medium viewports where there's not as much space available. The current placement works well enough in all sizes, so that's the easy go.

**Review by beta-ziliani — APPROVED** [review]
🚀

**Pull request merged**
