### PR TITLE
Tune link style

### PR DESCRIPTION
**Pull request by straight-shoota**
Link styling has historically been quite confusing with different styles in different places. The current designs also show different style: sometimes underlined black text, sometimes non-underlined light blue. The relaunch branch had followed this. But it's time to standardize on a unique link styling.

Links have the current color and an underline serves as indicator.

This removes the shrill light blue link color which leads to calmer visuals and a smoother reading experience.

Before:
grafik

After:
grafik

### CODE REVIEW

**Comment by beta-ziliani** [comment]
I'm asking a review from Joni to get his opinion. One thing that I don't love is the way it looks on large titles:
image

**Comment by straight-shoota** [comment]
Yeah, I suppose we could consider dropping the link style on headlines.

**Comment by beta-ziliani** [comment]
Actually, I just don't like it when it spawns two lines, but it looks good in one-liners. Just a nitpick I guess.

**Comment by straight-shoota** [comment]
We'll need shorter titles then 😆

**Comment by straight-shoota** [comment]
Running another idea, I think the underline could also have some color contrast to the font color:

grafik

grafik

**Comment by straight-shoota** [comment]
I went ahead with that. The result is more lightweight.

grafik

grafik

**Comment by beta-ziliani** [comment]
I like the new style better, but I still think the blog will look better without the underline

**Comment by straight-shoota** [comment]
I removed the underline on featured posts.

**Review by beta-ziliani — COMMENTED** [review]
The post back and forth nav items were always broken in this revamp?

image

**Comment by straight-shoota** [comment]
Yeah, that's a another issue on my list. Independent from this PR.

**Review by beta-ziliani — APPROVED** [review]

**Comment by jkicillof** [comment]
I agree on dropping blue but the underline should be only for body text, not headlines, nav or buttons

**Pull request merged**
