### PR TITLE
Add indicator for external links

### PR DESCRIPTION
**Pull request by straight-shoota**
We have an indicator for external links already in the top navigation. This expands that to the entire content. The indicator shows wether a link is internal or goes to a different website.
This style can be disabled, for example for links that are part of the UI chrome. Or in contexts where it's clear that a link is outgoing, such as the sponsors list.

Before:
grafik

After:
grafik

This PR goes on top of #557

### CODE REVIEW

**Comment by beta-ziliani** [comment]
In the Alumni section it looks a bit scrambled. I think here we might add the GH icon next to the name instead? The rest looks good.
image

**Comment by straight-shoota** [comment]
I'll remove the indicator there.

**Comment by straight-shoota** [comment]
Updated colors after #557

grafik

**Review by beta-ziliani — APPROVED** [review]
LGTM. A bit cramped here, but that can be tweaked in a second iteration.

image

**Pull request merged**
