### PR TITLE
Add conference sponsors & schedule

### PR DESCRIPTION
**Pull request by straight-shoota**

### CODE REVIEW

**Review by beta-ziliani — APPROVED** [review]
Icon alignments and the sizes of the button in the text aren't perfect, but we can fix those later.

**Comment by straight-shoota** [comment]
What icons? And what's wrong with button alignment?

**Comment by beta-ziliani** [comment]
sorry, I meant the logos, they aren't vertically centered, are they? And the last button (map) has a smaller font than the rest. Again, nitpicks.

**Comment by straight-shoota** [comment]
The logos are vertically center aligned. Maybe one of the logos if off-centered in itself? I don't think they look unbalanced, though.

The buttons are kinda intended to be different sizes. But we can align them.

**Pull request merged**
