### PR TITLE
Split `_generic.scss` in typography and site styles

### PR DESCRIPTION
**Pull request by straight-shoota**
This patch extracts generic typography styles into a dedicated file for the sake of separating concerns.

### CODE REVIEW

**Comment by beta-ziliani** [comment]
I'm not sure if this is the right separation. or at least, it sounds weird to me to have borders and margins as part of "typography".

**Comment by straight-shoota** [comment]
Borders of typographic elements such as headers or buttons belong to those elements.

**Comment by beta-ziliani** [comment]
IMHO (stressing the H), the concern here is "visuals" and applies to every component

**Review by beta-ziliani — APPROVED** [review]
To me `typography` is a bad name; it's not about typography, but about `basic` html components. But if this is a used named for such elements, so be it.

**Pull request merged**
