### PR TITLE
Fix `sponsors_logos_l` to require a logo

### PR DESCRIPTION
**Pull request by straight-shoota**
Ref https://github.com/crystal-lang/crystal-website/pull/792/files#r1622646393

### CODE REVIEW

**Comment by beta-ziliani** [comment]
We need a different approach to this. This is a very special case, but this person put that money and asked to have the link on the page, so it's only fair to have it there, even if with an empty picture.

**Comment by beta-ziliani** [comment]
PS: I asked him to put a pic a week ago, but didn't hear back from him yet.

**Comment by straight-shoota** [comment]
I suppose we could also add an empty image 🤷

**Comment by straight-shoota** [comment]
Obsolete due to https://github.com/crystal-lang/crystal-website/pull/797

**Pull request closed without merging**
