### PR TITLE
Cache bust assets

### PR DESCRIPTION
**Pull request by philnash**
I noticed that @matiasgarciaisaia had referenced my blog post in #12 so I thought I'd take a crack at the task. This PR does a number of things to improve front end performance and avoid caching issues with CSS and JS.

* Loads fonts using a <link> tag instead of `@import` in the CSS
* Stops loading Cousine weight 400, it isn't used
* Tidies up the pygments colour files using some Sass nesting
* Generates a single, minified stylesheet file with a digest in the filename
* Generates a single, minified javascript file with a digest in the filename

Ensure that when you build the site, `JEKYLL_ENV` is set to `production` otherwise there will be no minifying and no digest.

### CODE REVIEW

**Comment by philnash** [comment]
Hmm... this failed because Rack 2.0.1 requires Ruby >= 2.2.2 and the build is being run with 2.2.0.

I see that Travis is doing the build and then deploying (when on the master branch), I'll update the Ruby version to the latest in the 2.2.x series and try again.

**Comment by vtiffenberg** [comment]
The redesign has diverged quite a bit from master, so instead of merging this pull request I applied its suggestions in 9fd9cc, a00cd9 and 613b23, and will close. 
Thanks @philnash for the contribution.

**Comment by philnash** [comment]
Thanks @vtiffenberg!

**Comment by matiasgarciaisaia** [comment]
(I _really_ should have taken at least 20 seconds to thank you, @philnash, instead of waiting to work on this. Anyways - thank you very much! 🎉 )

**Comment by philnash** [comment]
No worries! Just glad to help out. Let me know if there's anywhere else I can pitch in.

**Pull request closed without merging**
